"""add field type configuration

Revision ID: 86258f2a6293
Revises: 84a60b385597
Create Date: 2026-09-17 15:50:30.722184

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86258f2a6293"
down_revision: str | Sequence[str] | None = "84a60b385597"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_field_options",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("field_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["inventory_fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("inventory_fields", sa.Column("max_length", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_fields", "max_length")
    op.drop_table("inventory_field_options")
    # ### end Alembic commands ###
